{
//=========Macro generated from canvas: c/c
//=========  (Thu Oct  6 00:31:30 2016) by ROOT version5.34/07
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   gStyle->SetOptStat(0);
   c->SetHighLightColor(2);
   c->Range(-7.553957,-0.1685185,52.39808,1.127778);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetGridx();
   c->SetGridy();
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.126);
   c->SetRightMargin(0.04);
   c->SetTopMargin(0.06);
   c->SetBottomMargin(0.13);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH1F *b1 = new TH1F("b1","           #scale[1.4]{#font[61]{CMS}} #font[52]{Simulation preliminary}                                                           14 TeV, 140 PU",50,0,50);
   b1->SetMinimum(0);
   b1->SetMaximum(1.05);
   b1->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   b1->SetLineColor(ci);
   b1->GetXaxis()->SetTitle("True muon p_{T} [GeV]");
   b1->GetXaxis()->SetLabelFont(42);
   b1->GetXaxis()->SetLabelSize(0.05);
   b1->GetXaxis()->SetTitleSize(0.05);
   b1->GetXaxis()->SetTitleOffset(1.2);
   b1->GetXaxis()->SetTitleFont(42);
   b1->GetYaxis()->SetTitle("Trigger efficiency");
   b1->GetYaxis()->SetNdivisions(520);
   b1->GetYaxis()->SetLabelFont(42);
   b1->GetYaxis()->SetLabelSize(0.05);
   b1->GetYaxis()->SetTitleSize(0.05);
   b1->GetYaxis()->SetTitleOffset(1.2);
   b1->GetYaxis()->SetTitleFont(42);
   b1->GetZaxis()->SetLabelFont(42);
   b1->GetZaxis()->SetLabelSize(0.035);
   b1->GetZaxis()->SetTitleSize(0.035);
   b1->GetZaxis()->SetTitleFont(42);
   b1->Draw("");
   
   TEfficiency * denom_clone_clone4 = new TEfficiency("denom_clone_clone","",50,0,50);
   
   denom_clone_clone4->SetConfidenceLevel(0.6826895);
   denom_clone_clone4->SetBetaAlpha(1);
   denom_clone_clone4->SetBetaBeta(1);
   denom_clone_clone4->SetWeight(1);
   denom_clone_clone4->SetStatisticOption(0);
   denom_clone_clone4->SetPosteriorMode(0);
   denom_clone_clone4->SetShortestInterval(0);
   denom_clone_clone4->SetTotalEvents(0,0);
   denom_clone_clone4->SetPassedEvents(0,0);
   denom_clone_clone4->SetTotalEvents(1,0);
   denom_clone_clone4->SetPassedEvents(1,0);
   denom_clone_clone4->SetTotalEvents(2,4);
   denom_clone_clone4->SetPassedEvents(2,0);
   denom_clone_clone4->SetTotalEvents(3,32);
   denom_clone_clone4->SetPassedEvents(3,6);
   denom_clone_clone4->SetTotalEvents(4,117);
   denom_clone_clone4->SetPassedEvents(4,43);
   denom_clone_clone4->SetTotalEvents(5,240);
   denom_clone_clone4->SetPassedEvents(5,168);
   denom_clone_clone4->SetTotalEvents(6,260);
   denom_clone_clone4->SetPassedEvents(6,242);
   denom_clone_clone4->SetTotalEvents(7,369);
   denom_clone_clone4->SetPassedEvents(7,364);
   denom_clone_clone4->SetTotalEvents(8,384);
   denom_clone_clone4->SetPassedEvents(8,377);
   denom_clone_clone4->SetTotalEvents(9,380);
   denom_clone_clone4->SetPassedEvents(9,373);
   denom_clone_clone4->SetTotalEvents(10,423);
   denom_clone_clone4->SetPassedEvents(10,415);
   denom_clone_clone4->SetTotalEvents(11,447);
   denom_clone_clone4->SetPassedEvents(11,436);
   denom_clone_clone4->SetTotalEvents(12,397);
   denom_clone_clone4->SetPassedEvents(12,387);
   denom_clone_clone4->SetTotalEvents(13,327);
   denom_clone_clone4->SetPassedEvents(13,319);
   denom_clone_clone4->SetTotalEvents(14,340);
   denom_clone_clone4->SetPassedEvents(14,334);
   denom_clone_clone4->SetTotalEvents(15,334);
   denom_clone_clone4->SetPassedEvents(15,324);
   denom_clone_clone4->SetTotalEvents(16,284);
   denom_clone_clone4->SetPassedEvents(16,281);
   denom_clone_clone4->SetTotalEvents(17,281);
   denom_clone_clone4->SetPassedEvents(17,278);
   denom_clone_clone4->SetTotalEvents(18,274);
   denom_clone_clone4->SetPassedEvents(18,269);
   denom_clone_clone4->SetTotalEvents(19,282);
   denom_clone_clone4->SetPassedEvents(19,271);
   denom_clone_clone4->SetTotalEvents(20,214);
   denom_clone_clone4->SetPassedEvents(20,214);
   denom_clone_clone4->SetTotalEvents(21,241);
   denom_clone_clone4->SetPassedEvents(21,237);
   denom_clone_clone4->SetTotalEvents(22,206);
   denom_clone_clone4->SetPassedEvents(22,204);
   denom_clone_clone4->SetTotalEvents(23,185);
   denom_clone_clone4->SetPassedEvents(23,183);
   denom_clone_clone4->SetTotalEvents(24,184);
   denom_clone_clone4->SetPassedEvents(24,180);
   denom_clone_clone4->SetTotalEvents(25,175);
   denom_clone_clone4->SetPassedEvents(25,174);
   denom_clone_clone4->SetTotalEvents(26,144);
   denom_clone_clone4->SetPassedEvents(26,143);
   denom_clone_clone4->SetTotalEvents(27,128);
   denom_clone_clone4->SetPassedEvents(27,124);
   denom_clone_clone4->SetTotalEvents(28,177);
   denom_clone_clone4->SetPassedEvents(28,173);
   denom_clone_clone4->SetTotalEvents(29,132);
   denom_clone_clone4->SetPassedEvents(29,129);
   denom_clone_clone4->SetTotalEvents(30,110);
   denom_clone_clone4->SetPassedEvents(30,107);
   denom_clone_clone4->SetTotalEvents(31,97);
   denom_clone_clone4->SetPassedEvents(31,95);
   denom_clone_clone4->SetTotalEvents(32,97);
   denom_clone_clone4->SetPassedEvents(32,93);
   denom_clone_clone4->SetTotalEvents(33,80);
   denom_clone_clone4->SetPassedEvents(33,79);
   denom_clone_clone4->SetTotalEvents(34,88);
   denom_clone_clone4->SetPassedEvents(34,86);
   denom_clone_clone4->SetTotalEvents(35,71);
   denom_clone_clone4->SetPassedEvents(35,68);
   denom_clone_clone4->SetTotalEvents(36,61);
   denom_clone_clone4->SetPassedEvents(36,60);
   denom_clone_clone4->SetTotalEvents(37,47);
   denom_clone_clone4->SetPassedEvents(37,46);
   denom_clone_clone4->SetTotalEvents(38,33);
   denom_clone_clone4->SetPassedEvents(38,33);
   denom_clone_clone4->SetTotalEvents(39,45);
   denom_clone_clone4->SetPassedEvents(39,44);
   denom_clone_clone4->SetTotalEvents(40,31);
   denom_clone_clone4->SetPassedEvents(40,30);
   denom_clone_clone4->SetTotalEvents(41,34);
   denom_clone_clone4->SetPassedEvents(41,33);
   denom_clone_clone4->SetTotalEvents(42,23);
   denom_clone_clone4->SetPassedEvents(42,23);
   denom_clone_clone4->SetTotalEvents(43,19);
   denom_clone_clone4->SetPassedEvents(43,19);
   denom_clone_clone4->SetTotalEvents(44,21);
   denom_clone_clone4->SetPassedEvents(44,21);
   denom_clone_clone4->SetTotalEvents(45,26);
   denom_clone_clone4->SetPassedEvents(45,25);
   denom_clone_clone4->SetTotalEvents(46,19);
   denom_clone_clone4->SetPassedEvents(46,19);
   denom_clone_clone4->SetTotalEvents(47,14);
   denom_clone_clone4->SetPassedEvents(47,14);
   denom_clone_clone4->SetTotalEvents(48,12);
   denom_clone_clone4->SetPassedEvents(48,12);
   denom_clone_clone4->SetTotalEvents(49,6);
   denom_clone_clone4->SetPassedEvents(49,6);
   denom_clone_clone4->SetTotalEvents(50,4);
   denom_clone_clone4->SetPassedEvents(50,3);
   denom_clone_clone4->SetTotalEvents(51,46);
   denom_clone_clone4->SetPassedEvents(51,46);
   denom_clone_clone4->SetFillColor(19);

   ci = TColor::GetColor("#0000ff");
   denom_clone_clone4->SetLineColor(ci);

   ci = TColor::GetColor("#0000ff");
   denom_clone_clone4->SetMarkerColor(ci);
   denom_clone_clone4->SetMarkerStyle(20);
   denom_clone_clone4->Draw("samep");
   
   TEfficiency * denom_clone_clone5 = new TEfficiency("denom_clone_clone","",50,0,50);
   
   denom_clone_clone5->SetConfidenceLevel(0.6826895);
   denom_clone_clone5->SetBetaAlpha(1);
   denom_clone_clone5->SetBetaBeta(1);
   denom_clone_clone5->SetWeight(1);
   denom_clone_clone5->SetStatisticOption(0);
   denom_clone_clone5->SetPosteriorMode(0);
   denom_clone_clone5->SetShortestInterval(0);
   denom_clone_clone5->SetTotalEvents(0,0);
   denom_clone_clone5->SetPassedEvents(0,0);
   denom_clone_clone5->SetTotalEvents(1,0);
   denom_clone_clone5->SetPassedEvents(1,0);
   denom_clone_clone5->SetTotalEvents(2,17);
   denom_clone_clone5->SetPassedEvents(2,5);
   denom_clone_clone5->SetTotalEvents(3,90);
   denom_clone_clone5->SetPassedEvents(3,23);
   denom_clone_clone5->SetTotalEvents(4,295);
   denom_clone_clone5->SetPassedEvents(4,103);
   denom_clone_clone5->SetTotalEvents(5,581);
   denom_clone_clone5->SetPassedEvents(5,351);
   denom_clone_clone5->SetTotalEvents(6,764);
   denom_clone_clone5->SetPassedEvents(6,629);
   denom_clone_clone5->SetTotalEvents(7,889);
   denom_clone_clone5->SetPassedEvents(7,771);
   denom_clone_clone5->SetTotalEvents(8,915);
   denom_clone_clone5->SetPassedEvents(8,807);
   denom_clone_clone5->SetTotalEvents(9,1062);
   denom_clone_clone5->SetPassedEvents(9,954);
   denom_clone_clone5->SetTotalEvents(10,1006);
   denom_clone_clone5->SetPassedEvents(10,919);
   denom_clone_clone5->SetTotalEvents(11,1023);
   denom_clone_clone5->SetPassedEvents(11,931);
   denom_clone_clone5->SetTotalEvents(12,900);
   denom_clone_clone5->SetPassedEvents(12,832);
   denom_clone_clone5->SetTotalEvents(13,877);
   denom_clone_clone5->SetPassedEvents(13,817);
   denom_clone_clone5->SetTotalEvents(14,848);
   denom_clone_clone5->SetPassedEvents(14,773);
   denom_clone_clone5->SetTotalEvents(15,829);
   denom_clone_clone5->SetPassedEvents(15,770);
   denom_clone_clone5->SetTotalEvents(16,788);
   denom_clone_clone5->SetPassedEvents(16,728);
   denom_clone_clone5->SetTotalEvents(17,742);
   denom_clone_clone5->SetPassedEvents(17,689);
   denom_clone_clone5->SetTotalEvents(18,708);
   denom_clone_clone5->SetPassedEvents(18,660);
   denom_clone_clone5->SetTotalEvents(19,613);
   denom_clone_clone5->SetPassedEvents(19,574);
   denom_clone_clone5->SetTotalEvents(20,560);
   denom_clone_clone5->SetPassedEvents(20,523);
   denom_clone_clone5->SetTotalEvents(21,483);
   denom_clone_clone5->SetPassedEvents(21,457);
   denom_clone_clone5->SetTotalEvents(22,450);
   denom_clone_clone5->SetPassedEvents(22,423);
   denom_clone_clone5->SetTotalEvents(23,441);
   denom_clone_clone5->SetPassedEvents(23,417);
   denom_clone_clone5->SetTotalEvents(24,365);
   denom_clone_clone5->SetPassedEvents(24,341);
   denom_clone_clone5->SetTotalEvents(25,326);
   denom_clone_clone5->SetPassedEvents(25,303);
   denom_clone_clone5->SetTotalEvents(26,303);
   denom_clone_clone5->SetPassedEvents(26,276);
   denom_clone_clone5->SetTotalEvents(27,299);
   denom_clone_clone5->SetPassedEvents(27,277);
   denom_clone_clone5->SetTotalEvents(28,282);
   denom_clone_clone5->SetPassedEvents(28,252);
   denom_clone_clone5->SetTotalEvents(29,232);
   denom_clone_clone5->SetPassedEvents(29,214);
   denom_clone_clone5->SetTotalEvents(30,183);
   denom_clone_clone5->SetPassedEvents(30,171);
   denom_clone_clone5->SetTotalEvents(31,167);
   denom_clone_clone5->SetPassedEvents(31,155);
   denom_clone_clone5->SetTotalEvents(32,140);
   denom_clone_clone5->SetPassedEvents(32,132);
   denom_clone_clone5->SetTotalEvents(33,138);
   denom_clone_clone5->SetPassedEvents(33,130);
   denom_clone_clone5->SetTotalEvents(34,99);
   denom_clone_clone5->SetPassedEvents(34,95);
   denom_clone_clone5->SetTotalEvents(35,112);
   denom_clone_clone5->SetPassedEvents(35,106);
   denom_clone_clone5->SetTotalEvents(36,85);
   denom_clone_clone5->SetPassedEvents(36,82);
   denom_clone_clone5->SetTotalEvents(37,77);
   denom_clone_clone5->SetPassedEvents(37,72);
   denom_clone_clone5->SetTotalEvents(38,76);
   denom_clone_clone5->SetPassedEvents(38,76);
   denom_clone_clone5->SetTotalEvents(39,44);
   denom_clone_clone5->SetPassedEvents(39,40);
   denom_clone_clone5->SetTotalEvents(40,44);
   denom_clone_clone5->SetPassedEvents(40,40);
   denom_clone_clone5->SetTotalEvents(41,34);
   denom_clone_clone5->SetPassedEvents(41,32);
   denom_clone_clone5->SetTotalEvents(42,24);
   denom_clone_clone5->SetPassedEvents(42,23);
   denom_clone_clone5->SetTotalEvents(43,25);
   denom_clone_clone5->SetPassedEvents(43,23);
   denom_clone_clone5->SetTotalEvents(44,22);
   denom_clone_clone5->SetPassedEvents(44,20);
   denom_clone_clone5->SetTotalEvents(45,17);
   denom_clone_clone5->SetPassedEvents(45,15);
   denom_clone_clone5->SetTotalEvents(46,14);
   denom_clone_clone5->SetPassedEvents(46,13);
   denom_clone_clone5->SetTotalEvents(47,12);
   denom_clone_clone5->SetPassedEvents(47,12);
   denom_clone_clone5->SetTotalEvents(48,9);
   denom_clone_clone5->SetPassedEvents(48,9);
   denom_clone_clone5->SetTotalEvents(49,14);
   denom_clone_clone5->SetPassedEvents(49,13);
   denom_clone_clone5->SetTotalEvents(50,6);
   denom_clone_clone5->SetPassedEvents(50,6);
   denom_clone_clone5->SetTotalEvents(51,32);
   denom_clone_clone5->SetPassedEvents(51,31);
   denom_clone_clone5->SetFillColor(19);

   ci = TColor::GetColor("#ff0000");
   denom_clone_clone5->SetLineColor(ci);

   ci = TColor::GetColor("#ff0000");
   denom_clone_clone5->SetMarkerColor(ci);
   denom_clone_clone5->SetMarkerStyle(21);
   denom_clone_clone5->Draw("samep");
   
   TEfficiency * denom_clone_clone6 = new TEfficiency("denom_clone_clone","",50,0,50);
   
   denom_clone_clone6->SetConfidenceLevel(0.6826895);
   denom_clone_clone6->SetBetaAlpha(1);
   denom_clone_clone6->SetBetaBeta(1);
   denom_clone_clone6->SetWeight(1);
   denom_clone_clone6->SetStatisticOption(0);
   denom_clone_clone6->SetPosteriorMode(0);
   denom_clone_clone6->SetShortestInterval(0);
   denom_clone_clone6->SetTotalEvents(0,0);
   denom_clone_clone6->SetPassedEvents(0,0);
   denom_clone_clone6->SetTotalEvents(1,1);
   denom_clone_clone6->SetPassedEvents(1,1);
   denom_clone_clone6->SetTotalEvents(2,15);
   denom_clone_clone6->SetPassedEvents(2,6);
   denom_clone_clone6->SetTotalEvents(3,26);
   denom_clone_clone6->SetPassedEvents(3,9);
   denom_clone_clone6->SetTotalEvents(4,95);
   denom_clone_clone6->SetPassedEvents(4,34);
   denom_clone_clone6->SetTotalEvents(5,161);
   denom_clone_clone6->SetPassedEvents(5,76);
   denom_clone_clone6->SetTotalEvents(6,239);
   denom_clone_clone6->SetPassedEvents(6,111);
   denom_clone_clone6->SetTotalEvents(7,263);
   denom_clone_clone6->SetPassedEvents(7,141);
   denom_clone_clone6->SetTotalEvents(8,279);
   denom_clone_clone6->SetPassedEvents(8,173);
   denom_clone_clone6->SetTotalEvents(9,300);
   denom_clone_clone6->SetPassedEvents(9,183);
   denom_clone_clone6->SetTotalEvents(10,278);
   denom_clone_clone6->SetPassedEvents(10,183);
   denom_clone_clone6->SetTotalEvents(11,290);
   denom_clone_clone6->SetPassedEvents(11,202);
   denom_clone_clone6->SetTotalEvents(12,269);
   denom_clone_clone6->SetPassedEvents(12,177);
   denom_clone_clone6->SetTotalEvents(13,248);
   denom_clone_clone6->SetPassedEvents(13,161);
   denom_clone_clone6->SetTotalEvents(14,217);
   denom_clone_clone6->SetPassedEvents(14,154);
   denom_clone_clone6->SetTotalEvents(15,197);
   denom_clone_clone6->SetPassedEvents(15,134);
   denom_clone_clone6->SetTotalEvents(16,212);
   denom_clone_clone6->SetPassedEvents(16,146);
   denom_clone_clone6->SetTotalEvents(17,180);
   denom_clone_clone6->SetPassedEvents(17,130);
   denom_clone_clone6->SetTotalEvents(18,138);
   denom_clone_clone6->SetPassedEvents(18,100);
   denom_clone_clone6->SetTotalEvents(19,139);
   denom_clone_clone6->SetPassedEvents(19,102);
   denom_clone_clone6->SetTotalEvents(20,134);
   denom_clone_clone6->SetPassedEvents(20,105);
   denom_clone_clone6->SetTotalEvents(21,118);
   denom_clone_clone6->SetPassedEvents(21,82);
   denom_clone_clone6->SetTotalEvents(22,99);
   denom_clone_clone6->SetPassedEvents(22,62);
   denom_clone_clone6->SetTotalEvents(23,73);
   denom_clone_clone6->SetPassedEvents(23,50);
   denom_clone_clone6->SetTotalEvents(24,74);
   denom_clone_clone6->SetPassedEvents(24,47);
   denom_clone_clone6->SetTotalEvents(25,48);
   denom_clone_clone6->SetPassedEvents(25,37);
   denom_clone_clone6->SetTotalEvents(26,51);
   denom_clone_clone6->SetPassedEvents(26,38);
   denom_clone_clone6->SetTotalEvents(27,37);
   denom_clone_clone6->SetPassedEvents(27,29);
   denom_clone_clone6->SetTotalEvents(28,27);
   denom_clone_clone6->SetPassedEvents(28,21);
   denom_clone_clone6->SetTotalEvents(29,21);
   denom_clone_clone6->SetPassedEvents(29,17);
   denom_clone_clone6->SetTotalEvents(30,20);
   denom_clone_clone6->SetPassedEvents(30,18);
   denom_clone_clone6->SetTotalEvents(31,12);
   denom_clone_clone6->SetPassedEvents(31,10);
   denom_clone_clone6->SetTotalEvents(32,11);
   denom_clone_clone6->SetPassedEvents(32,10);
   denom_clone_clone6->SetTotalEvents(33,11);
   denom_clone_clone6->SetPassedEvents(33,9);
   denom_clone_clone6->SetTotalEvents(34,6);
   denom_clone_clone6->SetPassedEvents(34,6);
   denom_clone_clone6->SetTotalEvents(35,5);
   denom_clone_clone6->SetPassedEvents(35,2);
   denom_clone_clone6->SetTotalEvents(36,1);
   denom_clone_clone6->SetPassedEvents(36,1);
   denom_clone_clone6->SetTotalEvents(37,0);
   denom_clone_clone6->SetPassedEvents(37,0);
   denom_clone_clone6->SetTotalEvents(38,0);
   denom_clone_clone6->SetPassedEvents(38,0);
   denom_clone_clone6->SetTotalEvents(39,1);
   denom_clone_clone6->SetPassedEvents(39,1);
   denom_clone_clone6->SetTotalEvents(40,1);
   denom_clone_clone6->SetPassedEvents(40,1);
   denom_clone_clone6->SetTotalEvents(41,0);
   denom_clone_clone6->SetPassedEvents(41,0);
   denom_clone_clone6->SetTotalEvents(42,0);
   denom_clone_clone6->SetPassedEvents(42,0);
   denom_clone_clone6->SetTotalEvents(43,0);
   denom_clone_clone6->SetPassedEvents(43,0);
   denom_clone_clone6->SetTotalEvents(44,0);
   denom_clone_clone6->SetPassedEvents(44,0);
   denom_clone_clone6->SetTotalEvents(45,0);
   denom_clone_clone6->SetPassedEvents(45,0);
   denom_clone_clone6->SetTotalEvents(46,0);
   denom_clone_clone6->SetPassedEvents(46,0);
   denom_clone_clone6->SetTotalEvents(47,0);
   denom_clone_clone6->SetPassedEvents(47,0);
   denom_clone_clone6->SetTotalEvents(48,0);
   denom_clone_clone6->SetPassedEvents(48,0);
   denom_clone_clone6->SetTotalEvents(49,0);
   denom_clone_clone6->SetPassedEvents(49,0);
   denom_clone_clone6->SetTotalEvents(50,0);
   denom_clone_clone6->SetPassedEvents(50,0);
   denom_clone_clone6->SetTotalEvents(51,0);
   denom_clone_clone6->SetPassedEvents(51,0);
   denom_clone_clone6->SetFillColor(19);

   ci = TColor::GetColor("#009900");
   denom_clone_clone6->SetLineColor(ci);

   ci = TColor::GetColor("#009900");
   denom_clone_clone6->SetMarkerColor(ci);
   denom_clone_clone6->SetMarkerStyle(22);
   denom_clone_clone6->Draw("samep");
   TLatex *   tex = new TLatex(0.5,0.6,"Prompt L1Mu algorithm");
tex->SetNDC();
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.5,0.5,"|#eta|<2.4, p_{T}^{L1}>5 GeV");
tex->SetNDC();
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.5,0.2,0.9,0.45,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("denom_clone_clone","|d_{xy}|<5 cm","lp");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#0000ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("denom_clone_clone","5 <|d_{xy}|<50 cm","lp");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#ff0000");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("denom_clone_clone","50 <|d_{xy}|<100 cm","lp");

   ci = TColor::GetColor("#009900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#009900");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0,0.942,1,1,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("           #scale[1.4]{#font[61]{CMS}} #font[52]{Simulation preliminary}                                                           14 TeV, 140 PU");
   pt->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
