{
//=========Macro generated from canvas: c/c
//=========  (Sat Aug  6 18:00:20 2016) by ROOT version5.34/07
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.126);
   c->SetRightMargin(0.04);
   c->SetTopMargin(0.06);
   c->SetBottomMargin(0.13);
   c->SetFrameBorderMode(0);
   
   TH1F *GenMuEta_leading_random_pt10 = new TH1F("GenMuEta_leading_random_pt10","",100,-5,5);
   GenMuEta_leading_random_pt10->SetBinContent(6,1);
   GenMuEta_leading_random_pt10->SetBinContent(11,2);
   GenMuEta_leading_random_pt10->SetBinContent(13,1);
   GenMuEta_leading_random_pt10->SetBinContent(14,1);
   GenMuEta_leading_random_pt10->SetBinContent(16,2);
   GenMuEta_leading_random_pt10->SetBinContent(17,1);
   GenMuEta_leading_random_pt10->SetBinContent(18,2);
   GenMuEta_leading_random_pt10->SetBinContent(19,5);
   GenMuEta_leading_random_pt10->SetBinContent(20,1);
   GenMuEta_leading_random_pt10->SetBinContent(21,5);
   GenMuEta_leading_random_pt10->SetBinContent(22,4);
   GenMuEta_leading_random_pt10->SetBinContent(23,1);
   GenMuEta_leading_random_pt10->SetBinContent(24,2);
   GenMuEta_leading_random_pt10->SetBinContent(25,3);
   GenMuEta_leading_random_pt10->SetBinContent(26,7);
   GenMuEta_leading_random_pt10->SetBinContent(27,2);
   GenMuEta_leading_random_pt10->SetBinContent(28,4);
   GenMuEta_leading_random_pt10->SetBinContent(29,5);
   GenMuEta_leading_random_pt10->SetBinContent(30,7);
   GenMuEta_leading_random_pt10->SetBinContent(31,4);
   GenMuEta_leading_random_pt10->SetBinContent(32,5);
   GenMuEta_leading_random_pt10->SetBinContent(33,2);
   GenMuEta_leading_random_pt10->SetBinContent(34,4);
   GenMuEta_leading_random_pt10->SetBinContent(35,8);
   GenMuEta_leading_random_pt10->SetBinContent(36,8);
   GenMuEta_leading_random_pt10->SetBinContent(37,6);
   GenMuEta_leading_random_pt10->SetBinContent(38,8);
   GenMuEta_leading_random_pt10->SetBinContent(39,8);
   GenMuEta_leading_random_pt10->SetBinContent(40,7);
   GenMuEta_leading_random_pt10->SetBinContent(41,6);
   GenMuEta_leading_random_pt10->SetBinContent(42,4);
   GenMuEta_leading_random_pt10->SetBinContent(43,13);
   GenMuEta_leading_random_pt10->SetBinContent(44,4);
   GenMuEta_leading_random_pt10->SetBinContent(45,6);
   GenMuEta_leading_random_pt10->SetBinContent(46,2);
   GenMuEta_leading_random_pt10->SetBinContent(47,5);
   GenMuEta_leading_random_pt10->SetBinContent(48,6);
   GenMuEta_leading_random_pt10->SetBinContent(49,1);
   GenMuEta_leading_random_pt10->SetBinContent(51,1);
   GenMuEta_leading_random_pt10->SetBinContent(52,2);
   GenMuEta_leading_random_pt10->SetBinContent(53,4);
   GenMuEta_leading_random_pt10->SetBinContent(54,4);
   GenMuEta_leading_random_pt10->SetBinContent(55,6);
   GenMuEta_leading_random_pt10->SetBinContent(56,9);
   GenMuEta_leading_random_pt10->SetBinContent(57,8);
   GenMuEta_leading_random_pt10->SetBinContent(58,7);
   GenMuEta_leading_random_pt10->SetBinContent(59,6);
   GenMuEta_leading_random_pt10->SetBinContent(60,3);
   GenMuEta_leading_random_pt10->SetBinContent(61,11);
   GenMuEta_leading_random_pt10->SetBinContent(62,7);
   GenMuEta_leading_random_pt10->SetBinContent(63,7);
   GenMuEta_leading_random_pt10->SetBinContent(64,8);
   GenMuEta_leading_random_pt10->SetBinContent(65,8);
   GenMuEta_leading_random_pt10->SetBinContent(66,6);
   GenMuEta_leading_random_pt10->SetBinContent(67,6);
   GenMuEta_leading_random_pt10->SetBinContent(68,5);
   GenMuEta_leading_random_pt10->SetBinContent(69,2);
   GenMuEta_leading_random_pt10->SetBinContent(70,4);
   GenMuEta_leading_random_pt10->SetBinContent(71,6);
   GenMuEta_leading_random_pt10->SetBinContent(72,1);
   GenMuEta_leading_random_pt10->SetBinContent(73,6);
   GenMuEta_leading_random_pt10->SetBinContent(74,4);
   GenMuEta_leading_random_pt10->SetBinContent(75,2);
   GenMuEta_leading_random_pt10->SetBinContent(76,5);
   GenMuEta_leading_random_pt10->SetBinContent(77,4);
   GenMuEta_leading_random_pt10->SetBinContent(78,4);
   GenMuEta_leading_random_pt10->SetBinContent(79,9);
   GenMuEta_leading_random_pt10->SetBinContent(81,2);
   GenMuEta_leading_random_pt10->SetBinContent(82,1);
   GenMuEta_leading_random_pt10->SetBinContent(83,2);
   GenMuEta_leading_random_pt10->SetBinContent(84,2);
   GenMuEta_leading_random_pt10->SetBinContent(85,2);
   GenMuEta_leading_random_pt10->SetBinContent(87,1);
   GenMuEta_leading_random_pt10->SetBinContent(88,1);
   GenMuEta_leading_random_pt10->SetBinContent(93,1);
   GenMuEta_leading_random_pt10->SetBinContent(94,1);
   GenMuEta_leading_random_pt10->SetBinContent(96,1);
   GenMuEta_leading_random_pt10->SetBinContent(99,1);
   GenMuEta_leading_random_pt10->SetEntries(333);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.615,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetFillStyle(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("GenMuEta_leading_random_pt10");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 333    ");
   text = ptstats->AddText("Mean  = 0.02361");
   text = ptstats->AddText("RMS   =  1.895");
   text = ptstats->AddText("Underflow =      0");
   text = ptstats->AddText("Overflow  =      0");
   text = ptstats->AddText("Integral =    333");
   text = ptstats->AddText("Skewness = 0.02725");
   ptstats->SetOptStat(11111111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   GenMuEta_leading_random_pt10->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(GenMuEta_leading_random_pt10);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   GenMuEta_leading_random_pt10->SetLineColor(ci);
   GenMuEta_leading_random_pt10->GetXaxis()->SetTitle("Muon #eta");
   GenMuEta_leading_random_pt10->GetXaxis()->SetLabelFont(42);
   GenMuEta_leading_random_pt10->GetXaxis()->SetLabelSize(0.035);
   GenMuEta_leading_random_pt10->GetXaxis()->SetTitleSize(0.035);
   GenMuEta_leading_random_pt10->GetXaxis()->SetTitleFont(42);
   GenMuEta_leading_random_pt10->GetYaxis()->SetTitle(" Entries");
   GenMuEta_leading_random_pt10->GetYaxis()->SetLabelFont(42);
   GenMuEta_leading_random_pt10->GetYaxis()->SetLabelSize(0.035);
   GenMuEta_leading_random_pt10->GetYaxis()->SetTitleSize(0.035);
   GenMuEta_leading_random_pt10->GetYaxis()->SetTitleFont(42);
   GenMuEta_leading_random_pt10->GetZaxis()->SetLabelFont(42);
   GenMuEta_leading_random_pt10->GetZaxis()->SetLabelSize(0.035);
   GenMuEta_leading_random_pt10->GetZaxis()->SetTitleSize(0.035);
   GenMuEta_leading_random_pt10->GetZaxis()->SetTitleFont(42);
   GenMuEta_leading_random_pt10->Draw("");
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
