{
//=========Macro generated from canvas: c/c
//=========  (Thu Aug 18 18:08:30 2016) by ROOT version5.34/07
   TCanvas *c = new TCanvas("c", "c",0,0,800,600);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.126);
   c->SetRightMargin(0.04);
   c->SetTopMargin(0.06);
   c->SetBottomMargin(0.13);
   c->SetFrameBorderMode(0);
   
   TH1F *GenMuEta_leading_random_pt10 = new TH1F("GenMuEta_leading_random_pt10","",100,-5,5);
   GenMuEta_leading_random_pt10->SetBinContent(1,1);
   GenMuEta_leading_random_pt10->SetBinContent(2,1);
   GenMuEta_leading_random_pt10->SetBinContent(6,1);
   GenMuEta_leading_random_pt10->SetBinContent(8,2);
   GenMuEta_leading_random_pt10->SetBinContent(9,4);
   GenMuEta_leading_random_pt10->SetBinContent(10,4);
   GenMuEta_leading_random_pt10->SetBinContent(11,3);
   GenMuEta_leading_random_pt10->SetBinContent(12,5);
   GenMuEta_leading_random_pt10->SetBinContent(13,6);
   GenMuEta_leading_random_pt10->SetBinContent(14,8);
   GenMuEta_leading_random_pt10->SetBinContent(15,10);
   GenMuEta_leading_random_pt10->SetBinContent(16,14);
   GenMuEta_leading_random_pt10->SetBinContent(17,8);
   GenMuEta_leading_random_pt10->SetBinContent(18,21);
   GenMuEta_leading_random_pt10->SetBinContent(19,24);
   GenMuEta_leading_random_pt10->SetBinContent(20,19);
   GenMuEta_leading_random_pt10->SetBinContent(21,27);
   GenMuEta_leading_random_pt10->SetBinContent(22,18);
   GenMuEta_leading_random_pt10->SetBinContent(23,32);
   GenMuEta_leading_random_pt10->SetBinContent(24,37);
   GenMuEta_leading_random_pt10->SetBinContent(25,38);
   GenMuEta_leading_random_pt10->SetBinContent(26,47);
   GenMuEta_leading_random_pt10->SetBinContent(27,33);
   GenMuEta_leading_random_pt10->SetBinContent(28,37);
   GenMuEta_leading_random_pt10->SetBinContent(29,37);
   GenMuEta_leading_random_pt10->SetBinContent(30,51);
   GenMuEta_leading_random_pt10->SetBinContent(31,52);
   GenMuEta_leading_random_pt10->SetBinContent(32,55);
   GenMuEta_leading_random_pt10->SetBinContent(33,55);
   GenMuEta_leading_random_pt10->SetBinContent(34,54);
   GenMuEta_leading_random_pt10->SetBinContent(35,55);
   GenMuEta_leading_random_pt10->SetBinContent(36,68);
   GenMuEta_leading_random_pt10->SetBinContent(37,80);
   GenMuEta_leading_random_pt10->SetBinContent(38,77);
   GenMuEta_leading_random_pt10->SetBinContent(39,66);
   GenMuEta_leading_random_pt10->SetBinContent(40,62);
   GenMuEta_leading_random_pt10->SetBinContent(41,74);
   GenMuEta_leading_random_pt10->SetBinContent(42,82);
   GenMuEta_leading_random_pt10->SetBinContent(43,82);
   GenMuEta_leading_random_pt10->SetBinContent(44,88);
   GenMuEta_leading_random_pt10->SetBinContent(45,81);
   GenMuEta_leading_random_pt10->SetBinContent(46,53);
   GenMuEta_leading_random_pt10->SetBinContent(47,52);
   GenMuEta_leading_random_pt10->SetBinContent(48,33);
   GenMuEta_leading_random_pt10->SetBinContent(49,20);
   GenMuEta_leading_random_pt10->SetBinContent(50,8);
   GenMuEta_leading_random_pt10->SetBinContent(51,9);
   GenMuEta_leading_random_pt10->SetBinContent(52,18);
   GenMuEta_leading_random_pt10->SetBinContent(53,39);
   GenMuEta_leading_random_pt10->SetBinContent(54,44);
   GenMuEta_leading_random_pt10->SetBinContent(55,52);
   GenMuEta_leading_random_pt10->SetBinContent(56,64);
   GenMuEta_leading_random_pt10->SetBinContent(57,60);
   GenMuEta_leading_random_pt10->SetBinContent(58,72);
   GenMuEta_leading_random_pt10->SetBinContent(59,73);
   GenMuEta_leading_random_pt10->SetBinContent(60,82);
   GenMuEta_leading_random_pt10->SetBinContent(61,64);
   GenMuEta_leading_random_pt10->SetBinContent(62,84);
   GenMuEta_leading_random_pt10->SetBinContent(63,68);
   GenMuEta_leading_random_pt10->SetBinContent(64,67);
   GenMuEta_leading_random_pt10->SetBinContent(65,67);
   GenMuEta_leading_random_pt10->SetBinContent(66,49);
   GenMuEta_leading_random_pt10->SetBinContent(67,72);
   GenMuEta_leading_random_pt10->SetBinContent(68,66);
   GenMuEta_leading_random_pt10->SetBinContent(69,61);
   GenMuEta_leading_random_pt10->SetBinContent(70,62);
   GenMuEta_leading_random_pt10->SetBinContent(71,57);
   GenMuEta_leading_random_pt10->SetBinContent(72,44);
   GenMuEta_leading_random_pt10->SetBinContent(73,53);
   GenMuEta_leading_random_pt10->SetBinContent(74,48);
   GenMuEta_leading_random_pt10->SetBinContent(75,41);
   GenMuEta_leading_random_pt10->SetBinContent(76,25);
   GenMuEta_leading_random_pt10->SetBinContent(77,31);
   GenMuEta_leading_random_pt10->SetBinContent(78,35);
   GenMuEta_leading_random_pt10->SetBinContent(79,28);
   GenMuEta_leading_random_pt10->SetBinContent(80,19);
   GenMuEta_leading_random_pt10->SetBinContent(81,26);
   GenMuEta_leading_random_pt10->SetBinContent(82,15);
   GenMuEta_leading_random_pt10->SetBinContent(83,14);
   GenMuEta_leading_random_pt10->SetBinContent(84,8);
   GenMuEta_leading_random_pt10->SetBinContent(85,14);
   GenMuEta_leading_random_pt10->SetBinContent(86,16);
   GenMuEta_leading_random_pt10->SetBinContent(87,12);
   GenMuEta_leading_random_pt10->SetBinContent(88,8);
   GenMuEta_leading_random_pt10->SetBinContent(89,4);
   GenMuEta_leading_random_pt10->SetBinContent(90,5);
   GenMuEta_leading_random_pt10->SetBinContent(91,7);
   GenMuEta_leading_random_pt10->SetBinContent(92,2);
   GenMuEta_leading_random_pt10->SetBinContent(93,5);
   GenMuEta_leading_random_pt10->SetBinContent(94,1);
   GenMuEta_leading_random_pt10->SetBinContent(95,1);
   GenMuEta_leading_random_pt10->SetBinContent(96,1);
   GenMuEta_leading_random_pt10->SetBinContent(98,1);
   GenMuEta_leading_random_pt10->SetEntries(3379);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.615,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetFillStyle(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("GenMuEta_leading_random_pt10");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 3379   ");
   text = ptstats->AddText("Mean  = 0.0323");
   text = ptstats->AddText("RMS   =  1.813");
   text = ptstats->AddText("Underflow =      0");
   text = ptstats->AddText("Overflow  =      0");
   text = ptstats->AddText("Integral =   3379");
   text = ptstats->AddText("Skewness = -0.003294");
   ptstats->SetOptStat(11111111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   GenMuEta_leading_random_pt10->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(GenMuEta_leading_random_pt10);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   GenMuEta_leading_random_pt10->SetLineColor(ci);
   GenMuEta_leading_random_pt10->GetXaxis()->SetTitle("Muon #eta");
   GenMuEta_leading_random_pt10->GetXaxis()->SetLabelFont(42);
   GenMuEta_leading_random_pt10->GetXaxis()->SetLabelSize(0.035);
   GenMuEta_leading_random_pt10->GetXaxis()->SetTitleSize(0.035);
   GenMuEta_leading_random_pt10->GetXaxis()->SetTitleFont(42);
   GenMuEta_leading_random_pt10->GetYaxis()->SetTitle(" Entries");
   GenMuEta_leading_random_pt10->GetYaxis()->SetLabelFont(42);
   GenMuEta_leading_random_pt10->GetYaxis()->SetLabelSize(0.035);
   GenMuEta_leading_random_pt10->GetYaxis()->SetTitleSize(0.035);
   GenMuEta_leading_random_pt10->GetYaxis()->SetTitleFont(42);
   GenMuEta_leading_random_pt10->GetZaxis()->SetLabelFont(42);
   GenMuEta_leading_random_pt10->GetZaxis()->SetLabelSize(0.035);
   GenMuEta_leading_random_pt10->GetZaxis()->SetTitleSize(0.035);
   GenMuEta_leading_random_pt10->GetZaxis()->SetTitleFont(42);
   GenMuEta_leading_random_pt10->Draw("");
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
